---
- hosts: poster
  remote_user: root
  tasks:
    - file: path=/opt/poster/bin/ state=directory
    - name: upload binary
      copy:
        src: ../bin/poster
        dest: /opt/poster/bin/poster
        mode: "+x"
    - name: upload service
      copy:
        src: ./poster.service
        dest: /etc/systemd/system
    - name: upload nginx config
      copy:
        src: ./poster.conf
        dest: /etc/nginx/sites-available
    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
    - name: restart service
      systemd:
        state: restarted
        daemon_reload: yes
        name: poster.service
