---
- hosts: teleport
  remote_user: root
  tasks:
    - file: path=/opt/teleport/bin/ state=directory
    - name: upload binary
      copy:
        src: ../bin/teleport
        dest: /opt/teleport/bin/teleport
        mode: "+x"
    - name: upload service
      copy:
        src: ./teleport.service
        dest: /etc/systemd/system
    - name: upload nginx config
      copy:
        src: ./teleport.conf
        dest: /etc/nginx/sites-enabled
    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
    - name: restart service
      systemd:
        state: restarted
        daemon_reload: yes
        name: poster.service
